### ISSUE TITLE
Implement listCommand test coverage in TransactionParserTest.java

### ISSUE THREAD

**Issue by SeeYangZhi** [AY2425S1-CS2103-F13-1/tp#110]

**Comment by GavinSin** [comment]
I moving this to v1.4 for further discussion. Reason: Personally, I feel there is no need for parser test for `listTxn` and `list` command as there is no parameter to test. The only thing to test is when `list` command in inputted, then the all persons are listed correctly in the PersonListPanel, vice versa for `listTxn`. I can add this in milestone v1.4 as part of local GUI testing.

**Comment by SeeYangZhi** [comment]
@GavinSin Follow up required for this.

**Comment by GavinSin** [comment]
Currently, this is in my nice to have todo list. if I have time, I will do.
What need to be done:
- In local GUI testing,
 - for filtered person list (by contact), after running list command, all persons are showed in left panel list.
 - for filtered transaction (by any filter), after running listTxn command, all transactions are showed in right panel list.

**Comment by seanlim** [comment]
Hmm, since the `RightPanel` retrieves data from the `filteredTransactionList`, we can test:

1. That `RightPanel` changes when `filteredTransactionList` changes.
2. `filteredTransactionList` changes when `listTxn` command is executed

**Comment by seanlim** [comment]
> Hmm, since the `RightPanel` retrieves data from the `filteredTransactionList`, we can simplify the tests to:
> 
> 1. That `RightPanel` displays the same transactions as in `filteredTransactionList`.
> 2. `filteredTransactionList` changes when `listTxn` command is executed

1 is trivial, 2 is already covered by the respective `ListCommandTest` classes
