### ISSUE TITLE
Relationship between `Person` and `Transaction`

### ISSUE THREAD

**Issue by seanlim** [AY2425S1-CS2103-F13-1/tp#142]
We have not formally defined referential integrity between `Person` and `Transaction`. When a person is deleted, what should happen to their transactions?

1. Should transactions immediately be deleted when a person is deleted? This matters because it will affect the way `LogicManager` needs to be restructured.
2. If not, should we do it such that the transaction storage simply ignores transactions with hanging references?

**Comment by SeeYangZhi** [comment]
@seanlim  What are some pros and cons of the different approaches? 

Currently, I am leaning towards if a `Person` gets deleted the underlying `Transaction` related to the `Person` should be deleted as well. 

We should then add an enhancement that is already suggested in the initial AB3 book to allow users to archive the storage incase of any accidental deletion.

**Comment by seanlim** [comment]
> @seanlim What are some pros and cons of the different approaches?
> 
> Currently, I am leaning towards if a `Person` gets deleted the underlying `Transaction` related to the `Person` should be deleted as well.
> 
> We should then add an enhancement that is already suggested in the initial AB3 book to allow users to archive the storage incase of any accidental deletion.

Apologies for my late response as I have been caught up with an exam. 

Yeah I agree with you, because the `JSON` files are supposed to be user-editable so we should keep it as "up to date" as possible
