### ISSUE TITLE
Empty transaction book on subsequent start

### ISSUE THREAD

**Issue by rollingpencil** [AY2425S1-CS2103-F13-1/tp#151]
Assumption:
- Fresh start:
<img width="459" alt="Screenshot 2024-10-22 at 11 35 30 AM" src="https://github.com/user-attachments/assets/7525759a-bf3f-4bae-945c-b1742a7b0bb8">

Steps:

1. Start the program:

<img width="816" alt="Screenshot 2024-10-22 at 11 36 43 AM" src="https://github.com/user-attachments/assets/61e1137b-0049-4f77-8e8c-b977b0191f15">

> Shows that the default data is loaded for both address book and transaction book

<img width="459" alt="Screenshot 2024-10-22 at 11 35 30 AM" src="https://github.com/user-attachments/assets/7525759a-bf3f-4bae-945c-b1742a7b0bb8">

2. Modify transaction book
<img width="816" alt="Screenshot 2024-10-22 at 11 41 12 AM" src="https://github.com/user-attachments/assets/f4d4c3c2-57c7-45f2-be4b-731572e9fc4c">

<img width="444" alt="Screenshot 2024-10-22 at 11 41 33 AM" src="https://github.com/user-attachments/assets/3d7e954c-ef64-4efc-830a-e3dea1da1320">

Only `transactionbook.json` has been recorded.

3. Stop and reopen:

<img width="817" alt="Screenshot 2024-10-22 at 11 42 41 AM" src="https://github.com/user-attachments/assets/6f6783a8-9bb0-4e7c-81a2-912800bf22d3">

Prior transactions in `transactionbook.json` are lost due to referential integrity (potentially?)

<img width="1020" alt="Screenshot 2024-10-22 at 11 44 18 AM" src="https://github.com/user-attachments/assets/ee70003c-7d49-4acb-ab38-a53b4801759c">

> On a side note, it seems that the transaction book stops parsing subsequent transactions when the a problematic transaction is parsed.

**Comment by seanlim** [comment]
Is this bug still present?

**Comment by seanlim** [comment]
Tested and verified that fixed by #155
