### ISSUE TITLE
Filter by Category

### ISSUE THREAD

**Issue by rollingpencil** [AY2425S1-CS2103-F13-1/tp#204]
Currently the `filterTxn` command only allows filtering by person, amount, description and date. It should also filter by categories to make it more useful.

Only for the backend

**Comment by SeeYangZhi** [comment]
Not sure how necessary/feasible is this on the UI side since categories are not fixed enums and are freely declared by users. @GavinSin need your input.

**Comment by rollingpencil** [comment]
Definitely a good-to-have feature. It could be implemented in a future release.

**Comment by rollingpencil** [comment]
Resolved by #357
