### ISSUE TITLE
UG: editTxn UG states index as optional and included uncessary phone number field

### ISSUE THREAD

**Issue by SeeYangZhi** [AY2425S1-CS2103-F13-1/tp#210]
<img width="762" alt="Screenshot 2024-10-29 at 10 10 27 PM" src="https://github.com/user-attachments/assets/329135c5-c072-4c14-bf46-c1762b5c9f72">
<img width="789" alt="Screenshot 2024-10-29 at 10 10 50 PM" src="https://github.com/user-attachments/assets/1e8cf7e1-dcf2-4753-b15c-d85d3547626a">

**Comment by seanlim** [comment]
Closed by #218
