### ISSUE TITLE
Implement ParserUtils.getPersonFromAddressBookIndex()

### ISSUE THREAD

**Issue by rollingpencil** [AY2425S1-CS2103-F13-1/tp#211]
The current implementation of the `addTxn` command makes the AddCommand() class take in multiple responsibilities of
- Creating the transaction
- Inserting into the transaction list.

Creating the transaction in the AddCommand is very coupled with the input parsed by the AddCommandParser.
Perhaps we could decouple the AddCommand from AddCommandParser by passing a created transaction object and moving the parsing of id to Person to the AddCommandParser with the use of ParserUtils.getPersonFromAddressBookIndex().

Todo:
- Implement `public Person getPersonFromAddressBookIndex(Index index)` in ParserUtils class
- Revert AddCommand constructor signature to `AddCommand(transaction)`

**Comment by SeeYangZhi** [comment]
To be more specific and to clarify, is it that we can abstract:

```
        List<Person> lastShownList = model.getFilteredPersonList();

        if (targetIndex.getZeroBased() >= lastShownList.size()) {
            throw new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
        }

        Person personToDelete = lastShownList.get(targetIndex.getZeroBased());
```
