### ISSUE TITLE
Make FilterCommand index based to be aligned with other commands

### ISSUE THREAD

**Issue by rollingpencil** [AY2425S1-CS2103-F13-1/tp#212]
Blocked by #211 
Format would be `filterTxn p/PERSON_INDEX ...`

**Comment by SeeYangZhi** [comment]
I am not sure if we wanna use the same index as the `PREFIX_PHONE`. On second thought I realised maybe we can stick to the current implementation, or like how the `FIND` is limited to names. Maybe we can make `filterTxn` to be specific to just `filterTxn INDEX [amt/AMOUNT] [desc/DESC] [cat/CAT]` ?

**Comment by SeeYangZhi** [comment]
May need more brains @seanlim @GavinSin @Dino-Nuggies

**Comment by rollingpencil** [comment]
I don't think it will be useful to force INDEX. One such use case I can think of is I know the amount to pay, but I forgot the person or description it was for. so it would be useful for me to execute `filterTxn amt/10.00` so that I have lesser transactions to comb through.

**Comment by SeeYangZhi** [comment]
> I don't think it will be useful to force INDEX. One such use case I can think of is I know the amount to pay, but I forgot the person or description it was for. so it would be useful for me to execute `filterTxn amt/10.00` so that I have lesser transactions to comb through.

Oh okay, nice. Agreed, then index should be optional, filterTxn [INDEX] [amt/AMOUNT] [desc/DESC] [cat/CAT].

Should we retain the current feature of filter by phone number then?

**Comment by rollingpencil** [comment]
Depends on how you want to weigh usability with specificity. Filtering by phone shows that the user knows exactly who they want to filter by while having the Index makes it more convenient for them.
