### ISSUE TITLE
Bug: Prevent referential integrity from breaking when the user edits the json file while the application is running

### ISSUE THREAD

**Issue by rollingpencil** [AY2425S1-CS2103-F13-1/tp#216]
We should force a rewrite of both transactionbook json and addressbook json when commands related to either books are executed. This helps to keep referential integrity just like the references in memory and overwrites potential changes written to json file by the user when the app is running.

**Comment by seanlim** [comment]
This is currently the case: 

https://github.com/AY2425S1-CS2103-F13-1/tp/blob/10cc003bfc0e497e8c46e9d3078345718371a86b/src/main/java/spleetwaise/address/logic/LogicManager.java#L64-L76

**Comment by SeeYangZhi** [comment]
@rollingpencil Any follow-up required for this? Else, please close the issue.

**Comment by rollingpencil** [comment]
No further follow up required.
