### ISSUE TITLE
FLAW: Logger Misleads About Data File Creation Upon Mac CMD+Q Quit

### ISSUE THREAD

**Issue by SeeYangZhi** [AY2425S1-CS2103-F13-1/tp#219]
When running the app on macOS, if a user quits the app using CMD+Q immediately after loading the app for the first time, without executing any commands, no data file is saved. However, the logger misleadingly suggests that a data file has been created, even though this is not the case.

#### **Steps to Reproduce:**
1. Run the app from scratch (with sample data provided).
2. Do **not** execute any commands.
3. Immediately quit the app using `CMD+Q` (macOS shortcut).
4. Observe that no data file is saved upon quitting the app.

#### **Expected Behavior:**
- The logger should not indicate that a data file has been created unless the file has actually been written to disk.
- The data file should either be saved automatically when quitting the app (CMD+Q) or the logger should correctly indicate that no file has been created.

#### **Observed Behavior:**
- The logger outputs a message suggesting that a data file has been created even though no file exists.
- May refer to the logger code in `MainApp.java`

#### **Additional Context:**
- When using the `exit` command to close the app, the data file is saved correctly.

**Comment by seanlim** [comment]
I think that the data file should be saved when the user `CMD Q`s

**Comment by SeeYangZhi** [comment]
> I think that the data file should be saved when the user `CMD Q`s
Agreed.
