### ISSUE TITLE
Discuss: Should `editTxn` support editing the person field of a Transaction?

### ISSUE THREAD

**Issue by SeeYangZhi** [AY2425S1-CS2103-F13-1/tp#220]

**Comment by SeeYangZhi** [comment]
@seanlim what is the rational behind adding this support initially when implementing `editTxn`?

**Comment by rollingpencil** [comment]
Wrong person/index when you entered the transaction but realised that it was for another person instead.
In a team meal setting, it would be finding out later on that you are supposed to pay another person instead of the one you initially thought who paid the bill.

**Comment by SeeYangZhi** [comment]
> Wrong person/index when you entered the transaction but realised that it was for another person instead. In a team meal setting, it would be finding out later on that you are supposed to pay another person instead of the one you initially thought who paid the bill.

Oh right, very valid. I shall test out the app more. Will close this issue if no further comments by tonight

**Comment by GavinSin** [comment]
> Wrong person/index when you entered the transaction but realised that it was for another person instead. In a team meal setting, it would be finding out later on that you are supposed to pay another person instead of the one you initially thought who paid the bill.

the existing `editTxn` already support swapping to another person for a transaction.

**Comment by SeeYangZhi** [comment]
> > Wrong person/index when you entered the transaction but realised that it was for another person instead. In a team meal setting, it would be finding out later on that you are supposed to pay another person instead of the one you initially thought who paid the bill.
> 
> the existing `editTxn` already support swapping to another person for a transaction.

@seanlim I just tested the app, it seems like `editTxn 1 p/12312321` does not edit the phone number of txn1, instead it seems to be checking whether the phone number 12312321 exists

<img width="1511" alt="Screenshot 2024-11-02 at 10 36 47 AM" src="https://github.com/user-attachments/assets/eaaa9669-956c-4f20-b139-72a97bae6bb9">

**Comment by Dino-Nuggies** [comment]
Since person is now referenced using Index, there is no need for phone number of be a field for transaction and hence it should not be able to edit it using editTxn

**Comment by rollingpencil** [comment]
I think, in this case, the phone number should be used exclusively for changing the person tied to the transaction. 
`editTxn 2 p/12345678` would make it easier to specify the person to change to as it is not dependent on the current person list.
`editTxn 2 pIndex/9` would require both person to be in the person list which may not always be the case.

**Comment by rollingpencil** [comment]
> > > Wrong person/index when you entered the transaction but realised that it was for another person instead. In a team meal setting, it would be finding out later on that you are supposed to pay another person instead of the one you initially thought who paid the bill.
> > 
> > 
> > the existing `editTxn` already support swapping to another person for a transaction.
> 
> @seanlim I just tested the app, it seems like `editTxn 1 p/12312321` does not edit the phone number of txn1, instead it seems to be checking whether the phone number 12312321 exists
> 
> <img alt="Screenshot 2024-11-02 at 10 36 47 AM" width="1511" src="https://private-user-images.githubusercontent.com/46666370/382439124-eaaa9669-956c-4f20-b139-72a97bae6bb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2OTgzODUsIm5iZiI6MTczMDY5ODA4NSwicGF0aCI6Ii80NjY2NjM3MC8zODI0MzkxMjQtZWFhYTk2NjktOTU2Yy00ZjIwLWIxMzktNzJhOTdiYWU2YmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA1MjgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MzA3Y2RjNDY2NzAyMDEyOGE4MmQ1NGZjODE2MGYxNzY4MWNkNTAyYmMwZTk0NTEyZTM0MmNlNWY2ZDg4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VtP3EJL_SwWmM4At3OYkeavX6wTpo2TpAqkus2SN2ZQ">


<img width="1798" alt="Screenshot 2024-11-04 at 1 27 51 PM" src="https://github.com/user-attachments/assets/c962a09c-47a8-440e-9db4-bfbb07e289c5">

Have you tried it with a valid phone number? It seems to be working.

**Comment by SeeYangZhi** [comment]
> > > > Wrong person/index when you entered the transaction but realised that it was for another person instead. In a team meal setting, it would be finding out later on that you are supposed to pay another person instead of the one you initially thought who paid the bill.
> 
> > > 
> 
> > > 
> 
> > > the existing `editTxn` already support swapping to another person for a transaction.
> 
> > 
> 
> > @seanlim I just tested the app, it seems like `editTxn 1 p/12312321` does not edit the phone number of txn1, instead it seems to be checking whether the phone number 12312321 exists
> 
> > 
> 
> > <img alt="Screenshot 2024-11-02 at 10 36 47 AM" width="1511" src="https://private-user-images.githubusercontent.com/46666370/382439124-eaaa9669-956c-4f20-b139-72a97bae6bb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2OTgzODUsIm5iZiI6MTczMDY5ODA4NSwicGF0aCI6Ii80NjY2NjM3MC8zODI0MzkxMjQtZWFhYTk2NjktOTU2Yy00ZjIwLWIxMzktNzJhOTdiYWU2YmI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA1MjgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MzA3Y2RjNDY2NzAyMDEyOGE4MmQ1NGZjODE2MGYxNzY4MWNkNTAyYmMwZTk0NTEyZTM0MmNlNWY2ZDg4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VtP3EJL_SwWmM4At3OYkeavX6wTpo2TpAqkus2SN2ZQ">
> 
> 
> 
> 
> 
> <img width="1798" alt="Screenshot 2024-11-04 at 1 27 51 PM" src="https://github.com/user-attachments/assets/c962a09c-47a8-440e-9db4-bfbb07e289c5">
> 
> 
> 
> Have you tried it with a valid phone number? It seems to be working.

I see, yes, this is indeed my mistake. We may want to specify the error message in this case, "Invalid phone number, phone number must exist in Addressbook.
