### ISSUE TITLE
Discuss: Key definitions to be added for DG

### ISSUE THREAD

**Issue by GavinSin** [AY2425S1-CS2103-F13-1/tp#222]
## Glossary
This Spleetwaise app is a _single-user_ application. Transactions and total balances are relative to <ins>_the user_</ins>.

**Undone** Transaction: A newly created transaction that is not yet completed.
**Positive** Amount Transaction: Indicates someone owes <ins>_the user_</ins> an amount.
**Negative** Amount Transaction: Indicates <ins>_the user_</ins> owes someone an amount.
**Done** Transaction: A completed transaction.
 - For a positive done txn, it indicates someone owed <ins>_the user_</ins> and the person has paid <ins>_the user_</ins> back.
 - For a negative done txn, it indicates <ins>_the user_</ins> owed someone and <ins>_the user_</ins> has paid the person back.

### Commands
`markDone`: Marks a transaction as **done**.
`markUndone`: Reverts a **done** transaction back to **undone** if it was marked as done by mistake.

### Default Behavior
The transaction list panel displays both _done_ and _undone_ transactions.
The total balance overview, showing "You owe" and "You are owed" amounts, includes both _done_ and _undone_ transactions.

**Comment by SeeYangZhi** [comment]
Undone Transaction: By default, a newly created transaction is set as undone - i.e. if the transaction is added as `addTxn 1 amt/12.3 desc/John owes me for dinner`, this transaction is not done, John still owes me.
Done Transaction: A completed transaction, referring to the previous e.g. once John has paid me, I will mark the txn as done.
