### ISSUE TITLE
Bug: Data loss when referential integrity is compromised

### ISSUE THREAD

**Issue by seanlim** [AY2425S1-CS2103-F13-1/tp#226]
## Steps to reproduce

1. Start up the program as per normal.
2. Execute a command to save data.
3. Quit the program.
4. Delete "Alex Yeoh"
5. Start up the program again.

There should be the following warning:

```
WARNING: Data file at data/addressbook.json could not be loaded. Will be starting with an empty TransactionBook.
```
**in this case `addressbook.json` should actually be `transactionbook.json`. I will create another issue to address this typo.**

All transactions are deleted as a result of one person from the address book being deleted manually.

## Desired behaviour

1. If `addressbook.json` is corrupted, then we wipe `transactionbook.json`
2. If `addressbook.json` is still intact but missing references, we should just ignore the transactions that are missing (leave them in the JSON file but just not load them).

**Comment by seanlim** [comment]
@SeeYangZhi @rollingpencil thoughts?

**Comment by rollingpencil** [comment]
The desired behaviour is what I have in mind too. Any invalid person ID references are discarded.

**Comment by SeeYangZhi** [comment]
> The desired behaviour is what I have in mind too. Any invalid person ID references are discarded.

Yeah, Qian Bo and I had a discussion about it the other day, agreed.

**Comment by seanlim** [comment]
Alright, I shall proceed

**Comment by SeeYangZhi** [comment]
Just wanna link back to the discussion that I think an archive function would be good since we are wiping it. I think it is `good to have` feature that we should have it planned for future iterations if this project is to be continued. For now we can aim to fix as much bugs as possible for the alpha release to prepare for PE.

**Comment by SeeYangZhi** [comment]
<img width="812" alt="Screenshot 2024-11-03 at 12 49 02 PM" src="https://github.com/user-attachments/assets/43399150-a41a-4585-ac14-f87e81a37583">
Would need to update the UG with the correct behaviour

**Comment by seanlim** [comment]
> <img alt="Screenshot 2024-11-03 at 12 49 02 PM" width="812" src="https://private-user-images.githubusercontent.com/46666370/382548456-43399150-a41a-4585-ac14-f87e81a37583.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTA0NTAsIm5iZiI6MTczMDcxMDE1MCwicGF0aCI6Ii80NjY2NjM3MC8zODI1NDg0NTYtNDMzOTkxNTAtYTQxYS00NTg1LWFjMTQtZjg3ZTgxYTM3NTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA4NDkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZGVlYzI0Y2MwMTM4YTcwMGQyY2M1OWM3Y2ZhYzgzNGUxYzI4OTg4YmE0NjU4MWMyYTVmNzNiMWNkMWJmYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ta_FuvVE4a_URrOeZ_SH8sxVjUk4SQt0iL3HouxLLu8"> @seanlim I think we should update the UG with the correct behaviour

Closing this issue first and creating a new documentation issue for this
