### ISSUE TITLE
App not saving files when force quit on macOS

### ISSUE THREAD

**Issue by SeeYangZhi** [AY2425S1-CS2103-F13-1/tp#232]
When the application is forced to quit on macOS, it does not have the opportunity to execute the stop() method in the Application class, which is where the save operations are typically performed. This results in unsaved data when the application is forced to quit.

Related to: https://github.com/AY2425S1-CS2103-F13-1/tp/issues/219

**Comment by rollingpencil** [comment]
![telegram-cloud-photo-size-5-6147698905278692783-y](https://github.com/user-attachments/assets/38afcae7-888e-4e07-8703-e46c9c5eab50)

Appears that stop is called twice when using the `exit` command.
