### ISSUE TITLE
Move addressbook UI components to address package

### ISSUE THREAD

**Issue by seanlim** [AY2425S1-CS2103-F13-1/tp#268]
I noticed that all of addressbook's UI components have been recently refactored into `commons`. Should maintain a clear separation between `address`|`transaction`|`common`

**Comment by SeeYangZhi** [comment]
Related issue: https://github.com/AY2425S1-CS2103-F13-1/tp/issues/105

**Comment by GavinSin** [comment]
Currently, all the UI components are in package `commons`, with the exception of transaction related UI components: `RightPanel`, `TransactionCard`, and `TransactionListPanel` in package transaction. Am I right to say, you want all UI components in package `commons`.
