### ISSUE TITLE
Add Transactions Categories

### ISSUE THREAD

**Issue by SeeYangZhi** [AY2425S1-CS2103-F13-1/tp#3]
As a student, I want to tag expenses so I can easily manage multiple transaction categories (e.g., I may be sharing rent, utilities, and groceries with roommates/friends) and search for them later.

**Comment by SeeYangZhi** [comment]
subtask of #1

**Comment by SeeYangZhi** [comment]
@AY2425S1-CS2103-F13-1/developers We may want to consider use case of this and if it overlaps with #27

**Comment by SeeYangZhi** [comment]
Let’s move this to v1.3 if there’s no capacity for PR to be submitted by 11:30 PM on 10/10/2024.

**Comment by SeeYangZhi** [comment]
This issue should be closed once `editTxn` is implemented to complete the functionality for txn category. #190

**Comment by Dino-Nuggies** [comment]
Closing issue now the editTxn is implemented
