### ISSUE TITLE
Refactor CommonModel to ModelManager

### ISSUE THREAD

**Issue by rollingpencil** [AY2425S1-CS2103-F13-1/tp#305]
<img width="769" alt="Screenshot 2024-11-06 at 7 05 27 PM" src="https://github.com/user-attachments/assets/af750890-47eb-4b45-9d2e-a27e805eebe5">

> implements its functionality using a concrete `{Component Name}Manager` class

CommonModel does not follow this convention.

**Comment by rollingpencil** [comment]
@seanlim Should we follow the `XXXModelManager` convention for CommonModel?

**Comment by seanlim** [comment]
> @seanlim Should we follow the `XXXModelManager` convention for CommonModel?

Hmm, I thought about it, and yeah I think we should. 

Renaming `Model` to `CommonModel` and `CommonModel` to `CommonModelManager`

**Comment by seanlim** [comment]
> > > @seanlim Should we follow the `XXXModelManager` convention for CommonModel?
> > 
> > 
> > Hmm, I thought about it, and yeah I think we should.
> > Renaming `Model` to `CommonModel` and `CommonModel` to `CommonModelManager`
> 
> While you are at it, could you also refactor `transactionParser` to `transactionBookParser` as discussed previously?
> 
> The DG should be updated accordingly as well.

of course, no problem!
