### ISSUE TITLE
Tag name and Categories name will overflow if too long

### ISSUE THREAD

**Issue by GavinSin** [AY2425S1-CS2103-F13-1/tp#341]
### The Problem:
![image](https://github.com/user-attachments/assets/3fcdcf52-4936-469a-a4d5-07a8820573c3)
While resizing the window allows us to view longer category names, there is a maximum width for the main window, which results in truncation when a category name exceeds this limit. Since users are unable to view the full text in any way, this can be considered incorrect behavior and, therefore, a bug.

### Proposed changes:
- Make category and tag in UI wrap text if too long.

### Relevant Issues:
- #370 
- #373 
- #375 
- #447

**Comment by SeeYangZhi** [comment]
Does this apply to tags in the address book panel?

But we do not expect normal users to have such extreme behaviours anyway. Good catch though and good to be defensive since we are not limiting the characters for cat and tag as of now.

**Comment by Dino-Nuggies** [comment]
I would consider this to be a category/tag implementation bug where we should definitely limit the amount of characters for both tags and categories as filtering for category/tag requires user to type out the full word that is used for matching

**Comment by GavinSin** [comment]
> Does this apply to tags in the address book panel?
> 
> But we do not expect normal users to have such extreme behaviours anyway. Good catch though and good to be defensive since we are not limiting the characters for cat and tag as of now.

Yupp it applies to tags in address book panel.
![image](https://github.com/user-attachments/assets/cd3bbced-c556-462e-b34d-57e273e35b82)

**Comment by GavinSin** [comment]
> I would consider this to be a category/tag implementation bug where we should definitely limit the amount of characters for both tags and categories as filtering for category/tag requires user to type out the full word that is used for string matching

Even though this is a UI bug, however after quite some tries I am unable to wrap the text in the `FlowPane`. _(even after adding Label text with `wrapText` property inside FlowPane)_ As such, I am agreeing with your implementation on limiting the amount of characters for both tag and categories.

**Comment by SeeYangZhi** [comment]
> after quite some tries

Should be doable, but if you don't have enough time to try and need to focus on other bugs, we can include this as future enhancement for UI.
<img width="763" alt="Screenshot 2024-11-09 at 3 49 27 PM" src="https://github.com/user-attachments/assets/8b5decaa-237c-4822-a9f7-0fbd4351df76">

**Comment by SeeYangZhi** [comment]
> I would consider this to be a category/tag implementation bug where we should definitely limit the amount of characters for both tags and categories as filtering for category/tag requires user to type out the full word that is used for string matching

I don't think we are able to do that due to feature freeze, need to check if it is allowed.
