### ISSUE TITLE
Bug: Invalid JSON amt field in json crashes the application

### ISSUE THREAD

**Issue by rollingpencil** [AY2425S1-CS2103-F13-1/tp#363]
Currently, if "amt": {} is written in the transaction book file for any of the transaction, it leads to a NullPointerException.

**Comment by SeeYangZhi** [comment]
Inspired by similar issues found during PE-D: 
- https://github.com/SeeYangZhi/ped/issues/15
- https://github.com/SeeYangZhi/ped/issues/14

**Comment by SeeYangZhi** [comment]
Tagged as severity high as the app crashes and will not be able to launch at all if users do not know to reinstall the app or clear the data folder to start afresh.

**Comment by SeeYangZhi** [comment]
<img width="765" alt="Screenshot 2024-11-09 at 8 46 19 PM" src="https://github.com/user-attachments/assets/fd4a795d-a67f-4d20-9ffe-167e70b67330">
This is a bug that is not an intended bahaviour.
