### ISSUE TITLE
[PE-D][Tester C] Trace of AddressBook found in GUI

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-1/tp#366]
![image.png](https://raw.githubusercontent.com/hazzle23/ped/main/files/7655f4cb-d4ce-4128-a9ea-b003dbefcae1.png)

On the bottom left part of the GUI, the path is to addressbook.json

Since the app goes beyond an address book app and also handle tracking transactions, the user might be confuse on why is the name of path is addressbook.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: hazzle23/ped#1

**Comment by seanlim** [comment]
The app is still reading data from this specified path, and so the user should know where to find the user-editable file.
