### ISSUE TITLE
[PE-D][Tester B] Misleading error message for large integers

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-1/tp#371]
### Steps to reproduce:
1. Enter an extremely large integer for any of the INDEX fields such that it would cause an integer overflow in Java

Expected error message:
![bug1.2.png](https://raw.githubusercontent.com/casperngeen/ped/main/files/63788ca3-ce2e-4090-9643-3bb409cacd53.png)

Actual error message:
![bug1.1.png](https://raw.githubusercontent.com/casperngeen/ped/main/files/9de89afb-2fd3-4006-b704-7a68de2a5ff6.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: casperngeen/ped#1

**Comment by seanlim** [comment]
The code actually covers for the case that an integer overflows, but weirdly, two different exceptions are thrown.
