### ISSUE TITLE
[PE-D][Tester E] Long transaction amounts will cause Ui to overflow into ellipsis

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-1/tp#389]
When provided with the input `addTxn 2 amt/99999999999999999999999999999999999 desc/testing`

The following was observed on the user interface. `You are Owed: ...`

![image.png](https://raw.githubusercontent.com/winstonlimjy/ped/main/files/ecea86e6-b506-492b-9f8d-c8eb713335aa.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: winstonlimjy/ped#3

**Comment by SeeYangZhi** [comment]
@GavinSin This is a good example of [extreme user behaviour](https://nus-cs2103-ay2425s1.github.io/website/admin/tp-pe.html#functionality-bugs-2) we could label as a `response.NotInScope` for multiple reasons, I will list just one simple reason based on the input used for testing by Tester E:
> 99999999999999999999999999999999999 represents 10^35, or 100 undecillion. This figure is astronomically higher than any current estimates of global money or wealth. Furthermore, it is extremely unreasonable to expect any students – our target users to possess any money of such an amount.

**Comment by SeeYangZhi** [comment]
@GavinSin We can still fix the UI related truncating issues as mentioned by prof here https://github.com/nus-cs2103-AY2425S1/forum/issues/629#issuecomment-2464891416

Do take a look and fix it if it is indeed a bug.

**Comment by GavinSin** [comment]
This is indeed a bug as when the amount shown in total balance is too long, it will be truncated and overflow into ellipsis. Even if resized window may not solve the issue as there is a max width on how large the main app can be. The proposed change is to add a vertical scrollbar when balance content is too long and wrapped. 

- #484
