### ISSUE TITLE
[PE-D][Tester A] Misuse of phone number by using it to match the person when editing transaction

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-1/tp#391]
When editing a transaction, phone number is used to identify the target person.
This is not a natural choice as phone number is hard to memory and can be complicated.

This is make the feature harder to use and less useful

I suggest to match with name field or the index in the address book which are more natural choices

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Jianwen0451/ped#6

**Comment by seanlim** [comment]
Will be resolved along with #446
