### ISSUE TITLE
[PE-D][Tester C] Long address is cropped

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-1/tp#392]
The address is cropped even when i already maximize the window

![image.png](https://raw.githubusercontent.com/hazzle23/ped/main/files/68ab198c-bd9d-46b7-b172-be3896071da2.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: hazzle23/ped#5

**Comment by seanlim** [comment]
You'd need to have a pretty long address for this to be a problem huh
