### ISSUE TITLE
[PE-D][Tester C] Accept domainless email

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-1/tp#404]
Email should have top level domain. However, this app still accept email without top level domain (e.g. don't have .com)

![image.png](https://raw.githubusercontent.com/hazzle23/ped/main/files/66f7cd97-f5b9-47c6-a1b6-9164e7c19070.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: hazzle23/ped#6

**Comment by SeeYangZhi** [comment]
It is as expected to accept such inputs based on our current email validation. If it violates the validation, error message will show as follows:

* The `EMAIL` input must follow the format `local-part@domain` and adhere to the following constraints:
  * The local-part should only contain alphanumeric characters and these special characters, excluding the parentheses, (`+_.-`). The local-part may not start or end with any special characters.
  * This is followed by a `@` and then a domain name. The domain name is made up of domain labels separated by periods.
  * The domain name must:
    * end with a domain label at least 2 characters long
    * have each domain label start and end with alphanumeric characters
    * have each domain label consist of alphanumeric characters, separated only by hyphens, if any.

<img width="836" alt="Screenshot 2024-11-09 at 5 40 40 PM" src="https://github.com/user-attachments/assets/64f9d448-14f5-45eb-9255-6b10413612ef">
Will address in #362 for validation related enhancements
