### ISSUE TITLE
[PE-D][Tester D] The sequence diagram for the Dual-parser setup has a missing return arrow

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-1/tp#415]
![image.png](https://raw.githubusercontent.com/maertan/ped/main/files/41fbd0d9-a9ad-49c9-9112-c7ddc33ee3e1.png)

Missing return arrow for LogicManager's activation bar. It's not strictly necessary, but I think it's better for the sake of consistency throughout the diagram.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: maertan/ped#13

**Comment by seanlim** [comment]
![image](https://github.com/user-attachments/assets/c9d3ca68-7910-41f4-9401-141f6a4c1fd9)
