### ISSUE TITLE
[PE-D][Tester A] [DG Bugs] Inaccurate subjects in the user story

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-1/tp#417]
You have defined your target users to be "Students".

However in your user story, you only refer the subject as "User". The user story should be user-centric and focus on the needs as a student. 

My suggestion is to change the subject of the user story and update the subject if you change the target user based on my suggestion later on ;)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Jianwen0451/ped#13

**Comment by SeeYangZhi** [comment]
> You have defined your target users to be "Students".
We have defined "users to be students." Subsequent mention of users, should be understood as students too.
