### ISSUE TITLE
[PE-D][Tester B] Add command allows for excessively long numbers

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-1/tp#421]
### Steps to reproduce:
1. Add a new person with an extremely long phone number, example: `p/987654329876543298765432987654329876543298765432987654329876543298765432987654329876543298765432987654329876543298765432987654329876543298765432987654329876543298765432987654329876543298765432987654329876543298765432987654329876543298765432987654329876543298765432`

![image.png](https://raw.githubusercontent.com/casperngeen/ped/main/files/b6ce53b2-e671-4cc4-a9d6-a3498cc8ceb8.png)

Might be a good idea to disallow excessively long phone numbers.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: casperngeen/ped#11

**Comment by SeeYangZhi** [comment]
A good example of extreme user input!
<img width="1046" alt="Screenshot 2024-11-09 at 2 43 22 PM" src="https://github.com/user-attachments/assets/50176338-3a35-4d2a-8687-1c5fdddecfde">
