### ISSUE TITLE
[PE-D][Tester A] [DG Bugs] NFR provided is not actually NFR

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-1/tp#426]
The NFR number 4 is not NFR in my opinion since it defines the features of the app. (Money are represented as Singapore dollar)

I suggest to remove this from NFR and move it into the user guide

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Jianwen0451/ped#16

**Comment by Dino-Nuggies** [comment]
This is a non-functional requirement as it defines a constraint on currency usage. By limiting all transactions to a single currency (SGD), it affects the scope and simplifies the system for the MVP. While it can be seen as a feature of the app, it is does not explicitly implemented. Therefore it doesn't specify a function that the system must perform but rather a boundary for initial operations, which is characteristic of non-functional requirements.
