### ISSUE TITLE
[PE-D][Tester C] Doesn't accept phone number with country code

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-1/tp#433]
Valid phone number with country code (e.g. +65) is not acceped

![image.png](https://raw.githubusercontent.com/hazzle23/ped/main/files/312d2673-7d39-44bf-8f21-e5b2c79ab538.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: hazzle23/ped#9

**Comment by SeeYangZhi** [comment]
Context of the app is NUS Students, most users should therefore not need country code. if needed, they can just input `6598869302`
