### ISSUE TITLE
[PE-D][Tester B] Typo in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-1/tp#434]
Typo in the `filterTxn` section of the user guide.

![image.png](https://raw.githubusercontent.com/casperngeen/ped/main/files/879122dd-7d47-4210-8c8a-d0e11b5b6142.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: casperngeen/ped#14

**Comment by Dino-Nuggies** [comment]
Thank you for the issue will be fixed for 1.6 release
