### ISSUE TITLE
[PE-D][Tester C] Command is case-insensitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103-F13-1/tp#438]
Typing `Add` and `add` represent the same intention from the user. Not allowing command to be capitalized and just mentioning `Unknown command` will cause confusion
![image.png](https://raw.githubusercontent.com/hazzle23/ped/main/files/437c634a-ae87-4ffa-b086-f0eb326a0250.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: hazzle23/ped#11

**Comment by SeeYangZhi** [comment]
Behaviour is clearly documented in UG and as expected
