### ISSUE TITLE
[PE-D][Tester E] Invalid name accepted.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-1/tp#445]
Although user guide states it allows the character `-`.

When providing a name of `------`, it was accepted

But there should not be a name where by `------` is accepted, after giving an input `add n/------ p/1234 e/123@123.com a/123` as no name is `------`.

![image.png](https://raw.githubusercontent.com/winstonlimjy/ped/main/files/445fa5ff-469d-4413-953c-4501317b1bb4.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: winstonlimjy/ped#15

**Comment by Dino-Nuggies** [comment]
Similarly to what we has mentioned for issue #382, [here](https://github.com/AY2425S1-CS2103-F13-1/tp/issues/382#issuecomment-2465526698), this is also an example of [extreme user behaviour](https://nus-cs2103-ay2425s1.github.io/website/admin/tp-pe.html#functionality-bugs-2). Our following explanation:

* The team does wish to support the ability for users to include `-` character in their names as to support a wider range of users with reason stated in this [post](https://www.quora.com/Why-do-some-people-have-an-apostrophe-hyphen-in-their-name) on why `-` can exists in certain ethnicity of people.
* While Tester E provided the name `------` as a possible name that our software is able to accept, the name `------` is rather nonsensical and does not serve any real purposes in identifying an individual
* Therefore in normal use cases by users, a name such as `------` will not be a name that would be used.

**Comment by SeeYangZhi** [comment]
> But there should not be a name where by `------` is accepted, after giving an input `add n/------ p/1234 e/123@123.com a/123` as no name is `------`.

Fully agree, and therefore we do not expect normal users to input such values.
