### ISSUE TITLE
[PE-D][Tester E] Click but have no action

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F13-1/tp#453]
I am able to click on the rows in both the tables but there are no action to follow up.

![image.png](https://raw.githubusercontent.com/winstonlimjy/ped/main/files/aa5ecd45-10fb-4864-abe1-4c226ad93600.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: winstonlimjy/ped#18

**Comment by Dino-Nuggies** [comment]
Documentation doesnt mention any specified functionality when clicking on any rows of items, therefore this is not a bug.
