### ISSUE TITLE
Consolidated Bugs Related to the Categories

### ISSUE THREAD

**Issue by Dino-Nuggies** [AY2425S1-CS2103-F13-1/tp#459]
Relevant issues:
- [ ] Wrong usage message with addTxn
  - Reported in: #367 

- [ ] Limit number of characters for categories
  - Reported in: #447
  - In relation to: #341

**Comment by SeeYangZhi** [comment]
> * [ ]  Limit number of characters for categories
>   
>   * Reported in: [[PE-D][Tester C] UI Overflow when category of transaction is too long #447](https://github.com/AY2425S1-CS2103-F13-1/tp/issues/447)
>   * In relation to: [Tag name and Categories name will overflow if too long #341](https://github.com/AY2425S1-CS2103-F13-1/tp/issues/341)

We should not add char limits to tags and categories now that we are under a feature freeze.
<img width="607" alt="Screenshot 2024-11-09 at 8 00 19 PM" src="https://github.com/user-attachments/assets/c8eef3e0-3d30-4fe3-b607-a028919adfdf">
