### ISSUE TITLE
Issues related to case sensitivity

### ISSUE THREAD

**Issue by rollingpencil** [AY2425S1-CS2103-F13-1/tp#464]
Command related:
- #438 
- https://github.com/AY2425S1-CS2103-F13-1/tp/issues/423

Status related:
- #444 

Since these are considered feature flaws
![telegram-cloud-photo-size-5-6158897736150269348-y](https://github.com/user-attachments/assets/97adf539-6837-430c-a8de-27e83a6658a3)

Remedy
- Update UG/DG to better reflect on case sensitivity in commands

**Comment by SeeYangZhi** [comment]
Potentially to consider case sensitivity improvements in planned enhancements - https://github.com/AY2425S1-CS2103-F13-1/tp/pull/362
