### ISSUE TITLE
Add Use cases to DG

### ISSUE THREAD

**Issue by SeeYangZhi** [AY2425S1-CS2103-F13-1/tp#61]
Give a few representative use cases (textual form) that need multiple steps to complete. e.g. Adding a tag to a person (assume the user needs to find the person first)

**Comment by GavinSin** [comment]
From the [2103t website](https://nus-cs2103-ay2425s1.github.io/website/schedule/week7/project.html), it mentions only need to add few representative use cases. Hence, 8 use cases are added only.
