### ISSUE TITLE
Add a parser for SpleetWaise commands

### ISSUE THREAD

**Issue by seanlim** [AY2425S1-CS2103-F13-1/tp#82]
To begin integrating SpleetWaise features, we need to first figure out how to add new `Command`s to the codebase. This issue tracks and hosts discussion pertaining to **adding** and **integrating** a `SpleetWaiseParser`class, which should mirror the functionality of [AddressBookParser](https://github.com/AY2425S1-CS2103-F13-1/tp/blob/master/src/main/java/seedu/address/logic/parser/AddressBookParser.java).

**This issue is critical because the way we integrate the parser will affect the way we structure our packages.**

# Separate package approach
Initially proposed by @seanlim

Build SpleetWaise features like an extension to Ab3: we shall add code into a **separate**, **mirrored** package named `spleetwaise` and integrate features by "injecting" them into `seedu.address`.

### Why separate?
We don't actually need to make a lot of changes to the way Ab3 fundamentally works. Isolating our code from the core operating parts of Ab3 will allow us to err less while we learn and get used to the structure of Ab3.

### Why mirrored?
We should mirror everything— even the internal package structure. Here is a preliminary screenshot of what this means:

<img width="322" alt="image" src="https://github.com/user-attachments/assets/3821fac4-e6d9-4291-802f-c23d0fdef8d4">

We should add code with the following heuristic in mind: 

> _"If `seedu.address` has X, should `spleetwaise` have X also?"_

The reason is so that we can ensure maximum portability of whatever we are building without necessarily understanding in-depth what each class/construct does in `seedu.address`.

## General principles
Here are some guidelines we should try to adhere to as much as possible:

1. **Keep our code separate from the `spleetwaise.address` package**: try as much as possible to isolate all new code to a separate `spleetwaise.transactions` package, making minimal changes to `spleetwaise.address` to integrate and inject our new features.
2. **Re-use as much as possible**: to ensure maximum ease of integration, we should try to re-use and conform to the original constructs of AddressBook.

**Comment by SeeYangZhi** [comment]
Would it be more intuitive if we rename the `seedu` package to `spleetwaise` and have the sub-packages of `address` and `transactions` under `spleetwaise` ?

**Comment by seanlim** [comment]
> Would it be more intuitive if we rename the `seedu` package to `spleetwaise` and have the sub-packages of `address` and `transactions` under `spleetwaise` ?

Woah that's a good idea, we could do:

```
src/
  spleetwaise.
    .core (will contain application driver logic, which we need to pull out)
    .address (Ab3)
    .transactions (new code)
```

**Comment by seanlim** [comment]
PR #83
